# ALLGEMEIN

bom: 2024.03.00
compose: 1.6.3
material3: 1.2.0
  
# LIBRARIES - Latest Versions
# wir nehmen an, dass alles immer so upgedatet wird, dass es von der neuesten Version abhängig ist

cachefileprovider: 0.3.1
feedbackmanager: 2.0.5
lumberjack: 6.0.4
kotpreferences: 0.4
kotbilling: 0.7
composedialogs: 1.0.6